# Generated by Django 2.2 on 2020-04-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('cpf', models.IntegerField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('picture', models.ImageField(blank=True, upload_to='<django.db.models.fields.CharField>-<django.db.models.fields.IntegerField>')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
