# Generated by Django 2.2 on 2020-04-21 13:52

from django.db import migrations

def create_data(apps, schema_editor):
    User = apps.get_model('users', 'Users')
    User(
        name = 'First User',
        cpf = 12345678901,
        email = 'first@user.com',
        password = 'firstuser',
        phone = '1191234-5678'
    )

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
